version: '3.8'
services:
  pitbull-database:
    container_name: pitbull-database
    hostname: pitbull-database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  pitbull-backend:
    container_name: pitbull-backend
    depends_on:
      - pitbull-database
    build: ../back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../back:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - PB_SERVER
      - PB_DATABASE
      - PB_USERNAME
      - PB_PASSWORD
      - PB_DRIVER="{ODBC Driver 17 for SQL Server}"
  pitbull-frontend:
    depends_on:
      - pitbull-backend
    container_name: pitbull-frontend
    build: ../front
    ports:
      - "8080:8080"




