version: '3.8'
services:
  pitbull-database:
    container_name: pitbull-database
    hostname: pitbull-database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
  pitbull-backend:
    container_name: pitbull-backend
    depends_on:
      - pitbull-database
    build: ../back
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ../back:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=pitbull-database
      - DATABASE_PORT=5432
      - PB_SERVER=
      - PB_DATABASE=
      - PB_USERNAME=
      - PB_PASSWORD=
      - PB_DRIVER=
  pitbull-frontend:
    depends_on:
      - pitbull-backend
    container_name: pitbull-frontend
    build: ../front
    ports:
      - "8080:8080"




