version: '3.8'
services:
  pitbull-database:
    container_name: pitbull-database
    hostname: pitbull-database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
  pitbull-backend:
    container_name: pitbull-backend
    depends_on:
      - pitbull-database
    build: ../back
    restart: unless-stopped
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../back:/app
    ports:
      - "8000:8000"
  pitbull-cron:
    container_name: pitbull-cron
    depends_on:
      - pitbull-backend
    build: ../back
    command: bash -c "python manage.py crontab add && cron -f"
    volumes:
      - ../back:/app
  pitbull-frontend:
    depends_on:
      - pitbull-backend
    container_name: pitbull-frontend
    build: ../front
    ports:
      - "80:80"




